import { formatNotesToHTML, notesToMarkdown, getDifficultyColor, getDifficultyIcon } from '../../utils/notesHelpers.js';

export function NotesViewer({ notes, topic, difficulty, notesId, onSave, onDownload, onCopy }) {
    const difficultyColor = getDifficultyColor(difficulty);
    const difficultyIcon = getDifficultyIcon(difficulty);
    const formattedContent = formatNotesToHTML(notes);
    const viewerId = `notes-viewer-${Date.now()}`;
    
    return `
        <div id="${viewerId}" class="bg-gradient-to-br from-[#1F2937] to-[#111827] rounded-2xl p-6 border border-[#374151] shadow-xl">
            <!-- Header -->
            <div class="flex items-center justify-between mb-6 pb-4 border-b border-[#374151]">
                <div class="flex items-center gap-3">
                    <div class="relative">
                        <div class="absolute inset-0 bg-gradient-to-r from-[#10B981] to-[#059669] rounded-xl blur-md opacity-0 group-hover:opacity-50 transition-opacity"></div>
                        <div class="relative w-11 h-11 bg-gradient-to-r from-[#10B981] to-[#059669] rounded-xl flex items-center justify-center shadow-lg">
                            <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6.042A8.967 8.967 0 006 3.75c-1.052 0-2.062.18-3 .512v14.25A8.987 8.987 0 016 18c2.305 0 4.408.867 6 2.292m0-14.25a8.966 8.966 0 016-2.292c1.052 0 2.062.18 3 .512v14.25A8.987 8.987 0 0018 18a8.967 8.967 0 00-6 2.292m0-14.25v14.25"></path>
                            </svg>
                        </div>
                    </div>
                    <div>
                        <h2 class="text-xl font-bold text-white">${escapeHtml(notes.title || `${topic} Notes`)}</h2>
                        <div class="flex items-center gap-2 mt-1">
                            <span class="px-2 py-0.5 text-xs rounded-full ${difficultyColor} flex items-center gap-1">
                                <span>${difficultyIcon}</span>
                                <span>${difficulty.charAt(0).toUpperCase() + difficulty.slice(1)}</span>
                            </span>
                            <span class="text-xs text-[#6B7280]">✨ Generated by AI</span>
                        </div>
                    </div>
                </div>
                
                <div class="flex gap-2">
                    <button id="copyNotesBtn-${viewerId}" class="copy-notes-btn p-2 bg-[#111827] rounded-lg hover:bg-[#1F2937] transition-all duration-300 group" title="Copy Notes">
                        <svg class="w-5 h-5 text-[#9CA3AF] group-hover:text-[#3B82F6] transition-colors" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"></path>
                        </svg>
                    </button>
                    <button id="downloadNotesBtn-${viewerId}" class="download-notes-btn p-2 bg-[#111827] rounded-lg hover:bg-[#1F2937] transition-all duration-300 group" title="Download as Markdown">
                        <svg class="w-5 h-5 text-[#9CA3AF] group-hover:text-[#3B82F6] transition-colors" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"></path>
                        </svg>
                    </button>
                    <button id="saveNotesBtn-${viewerId}" class="save-notes-btn p-2 bg-[#111827] rounded-lg hover:bg-[#1F2937] transition-all duration-300 group" title="Save to Collection">
                        <svg class="w-5 h-5 text-[#9CA3AF] group-hover:text-[#3B82F6] transition-colors" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 5a2 2 0 012-2h10a2 2 0 012 2v16l-7-3.5L5 21V5z"></path>
                        </svg>
                    </button>
                </div>
            </div>
            
            <!-- Notes Content -->
            <div class="notes-content prose prose-invert max-w-none">
                ${formattedContent}
            </div>
            
            <div class="mt-6 pt-4 border-t border-[#374151] text-center text-xs text-[#6B7280]">
                <span>💡 AI-generated notes • Save for later reference</span>
            </div>
        </div>
        
        <script>
            (function() {
                const copyBtn = document.getElementById('copyNotesBtn-${viewerId}');
                const downloadBtn = document.getElementById('downloadNotesBtn-${viewerId}');
                const saveBtn = document.getElementById('saveNotesBtn-${viewerId}');
                
                if (copyBtn) {
                    copyBtn.addEventListener('click', function(e) {
                        e.preventDefault();
                        e.stopPropagation();
                        if (window.handleCopyNotes) window.handleCopyNotes();
                    });
                }
                
                if (downloadBtn) {
                    downloadBtn.addEventListener('click', function(e) {
                        e.preventDefault();
                        e.stopPropagation();
                        if (window.handleDownloadNotes) window.handleDownloadNotes();
                    });
                }
                
                if (saveBtn) {
                    saveBtn.addEventListener('click', function(e) {
                        e.preventDefault();
                        e.stopPropagation();
                        if (window.handleSaveNotes) window.handleSaveNotes();
                    });
                }
                
                // Copy code buttons
                document.querySelectorAll('.copy-code-btn').forEach(btn => {
                    const newBtn = btn.cloneNode(true);
                    btn.parentNode.replaceChild(newBtn, btn);
                    
                    newBtn.addEventListener('click', function(e) {
                        e.preventDefault();
                        e.stopPropagation();
                        const code = this.dataset.code;
                        if (code) {
                            navigator.clipboard.writeText(code);
                            const originalText = this.innerHTML;
                            this.innerHTML = '✓ Copied!';
                            setTimeout(() => {
                                this.innerHTML = originalText;
                            }, 2000);
                        }
                    });
                });
            })();
        </script>
    `;
}

function escapeHtml(text) {
    if (!text) return '';
    const div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
}