// frontend/src/components/roadmap/RoadmapViewer.js

export function RoadmapViewer({ htmlContent, roadmapId, topic, onSave, onShare, onDownload }) {
    return `
        <div class="bg-gradient-to-br from-[#1F2937] to-[#111827] rounded-2xl p-6 border border-[#374151] shadow-xl">
            <div class="flex items-center justify-between mb-4">
                <div class="flex items-center gap-3">
                    <div class="w-10 h-10 bg-gradient-to-r from-[#10B981] to-[#059669] rounded-xl flex items-center justify-center">
                        <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 20l-5.447-2.724A1 1 0 013 16.382V5.618a1 1 0 011.447-.894L9 7m0 13l6-3m-6 3V7m6 10l4.553 2.276A1 1 0 0021 18.382V7.618a1 1 0 00-.553-.894L15 4m0 13V4m0 0L9 7"></path>
                        </svg>
                    </div>
                    <div>
                        <h3 class="text-lg font-bold text-white">${escapeHtml(topic)} Roadmap</h3>
                        <p class="text-xs text-[#9CA3AF]">Learning path generated by AI</p>
                    </div>
                </div>
                
                <div class="flex gap-2">
                    <button id="saveBtn-${roadmapId}" class="p-2 bg-[#111827] rounded-lg hover:bg-[#1F2937] transition-colors" title="Save to Collection">
                        <svg class="w-5 h-5 text-[#9CA3AF]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 5a2 2 0 012-2h10a2 2 0 012 2v16l-7-3.5L5 21V5z"></path>
                        </svg>
                    </button>
                    <button id="shareBtn-${roadmapId}" class="p-2 bg-[#111827] rounded-lg hover:bg-[#1F2937] transition-colors" title="Share Link">
                        <svg class="w-5 h-5 text-[#9CA3AF]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z"></path>
                        </svg>
                    </button>
                </div>
            </div>
            
            <!-- Roadmap Content - Clean Display -->
            <div class="bg-gradient-to-br from-[#0F172A] to-[#111827] rounded-xl p-8 border border-[#374151] text-center">
                <div class="mb-6">
                    <div class="w-20 h-20 mx-auto bg-gradient-to-r from-[#3B82F6] to-[#A78BFA] rounded-2xl flex items-center justify-center shadow-lg mb-4">
                        <svg class="w-10 h-10 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9 20l-5.447-2.724A1 1 0 013 16.382V5.618a1 1 0 011.447-.894L9 7m0 13l6-3m-6 3V7m6 10l4.553 2.276A1 1 0 0021 18.382V7.618a1 1 0 00-.553-.894L15 4m0 13V4m0 0L9 7"></path>
                        </svg>
                    </div>
                    <h2 class="text-2xl font-bold text-white mb-2">${escapeHtml(topic)} Learning Path</h2>
                    <p class="text-[#9CA3AF]">AI-generated roadmap to master ${escapeHtml(topic)}</p>
                </div>
                
                <!-- Topics List -->
                <div class="text-left space-y-3 max-h-96 overflow-y-auto custom-scrollbar">
                    <div class="p-3 bg-[#1F2937] rounded-xl border border-[#374151]">
                        <div class="flex items-center gap-3">
                            <div class="w-8 h-8 bg-[#3B82F6]/20 rounded-lg flex items-center justify-center">
                                <span class="text-[#3B82F6]">1</span>
                            </div>
                            <div>
                                <p class="font-medium text-white">Introduction to ${escapeHtml(topic)}</p>
                                <p class="text-xs text-[#9CA3AF]">Get started with basics</p>
                            </div>
                        </div>
                    </div>
                    <div class="p-3 bg-[#1F2937] rounded-xl border border-[#374151]">
                        <div class="flex items-center gap-3">
                            <div class="w-8 h-8 bg-[#3B82F6]/20 rounded-lg flex items-center justify-center">
                                <span class="text-[#3B82F6]">2</span>
                            </div>
                            <div>
                                <p class="font-medium text-white">Core Concepts</p>
                                <p class="text-xs text-[#9CA3AF]">Learn fundamental concepts</p>
                            </div>
                        </div>
                    </div>
                    <div class="p-3 bg-[#1F2937] rounded-xl border border-[#374151]">
                        <div class="flex items-center gap-3">
                            <div class="w-8 h-8 bg-[#3B82F6]/20 rounded-lg flex items-center justify-center">
                                <span class="text-[#3B82F6]">3</span>
                            </div>
                            <div>
                                <p class="font-medium text-white">Practice & Projects</p>
                                <p class="text-xs text-[#9CA3AF]">Hands-on learning</p>
                            </div>
                        </div>
                    </div>
                    <div class="p-3 bg-[#1F2937] rounded-xl border border-[#374151]">
                        <div class="flex items-center gap-3">
                            <div class="w-8 h-8 bg-[#3B82F6]/20 rounded-lg flex items-center justify-center">
                                <span class="text-[#3B82F6]">4</span>
                            </div>
                            <div>
                                <p class="font-medium text-white">Advanced Topics</p>
                                <p class="text-xs text-[#9CA3AF]">Take your skills further</p>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="mt-6 pt-4 border-t border-[#374151]">
                    <p class="text-sm text-[#6B7280]">✨ Roadmap generated with AI assistance</p>
                </div>
            </div>
            
            <div class="mt-4 pt-3 border-t border-[#374151] flex justify-between items-center text-xs text-[#6B7280]">
                <span>💡 Click "Save" to add to your collection</span>
                <span>ID: #${roadmapId}</span>
            </div>
        </div>
        
        <script>
            (function() {
                // Save button
                const saveBtn = document.getElementById('saveBtn-${roadmapId}');
                if (saveBtn && window.handleSaveRoadmap) {
                    saveBtn.addEventListener('click', () => window.handleSaveRoadmap(${roadmapId}));
                }
                
                // Share button
                const shareBtn = document.getElementById('shareBtn-${roadmapId}');
                if (shareBtn && window.handleShareRoadmap) {
                    shareBtn.addEventListener('click', () => window.handleShareRoadmap(${roadmapId}));
                }
            })();
        </script>
    `;
}

export function setupRoadmapViewer({ onSave, onShare, onDownload }) {
    console.log('RoadmapViewer setup complete');
}

function escapeHtml(text) {
    if (!text) return '';
    const div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
}